version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dados_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python:
    build: .
    container_name: python_data
    depends_on:
      - mysql
    volumes:
      - .:/app
    command: python python/test_mysql.py

volumes:
  mysql_data: